version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: 'main'
    schedule:
      interval: weekly
    ignore:
      # ignore all patch upgrades
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'zivkovicmilos'
